# 모든 테이블이 생성 시간, 수정 시간 그리고 soft delete를 위한 삭제 여부를 가지고 있다.
CREATE DATABASE IF NOT EXISTS CLUB_COMMUNITY;
DROP TABLE IF EXISTS CLUB_COMMUNITY.USERS;
# 사용자 테이블 : 계정, 비밀번호, 닉네임을 입력받는다.
# 계정과 별명은 중복이 불가능하다.
CREATE TABLE CLUB_COMMUNITY.USERS(
    ID              BIGINT      NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    ACCOUNT_ID      VARCHAR(16)	NOT NULL UNIQUE,
    PASSWORD        VARCHAR(100)NOT NULL,
    NICK_NAME       VARCHAR(12)	NOT NULL UNIQUE,
    CREATED_AT      TIMESTAMP   DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP   DEFAULT NOW() ON UPDATE NOW(),
    DELETED         BOOL        DEFAULT FALSE
);
DROP TABLE IF EXISTS CLUB_COMMUNITY.CLUBS;
# 소모임 테이블 : 소모임 이름과 소개를 입력받는다.
# 소모임을 만든 사용자의 ID와 가입된 사용자 수를 유지한다.
CREATE TABLE CLUB_COMMUNITY.CLUBS(
    ID              BIGINT      NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    OWNER_ID        BIGINT      NOT NULL,
    CLUB_NAME       VARCHAR(12)	NOT NULL UNIQUE,
    INTRODUCE       VARCHAR(100),
    MEMBER_NUM      INT         DEFAULT	0,
    CREATED_AT      TIMESTAMP   DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP   DEFAULT NOW() ON UPDATE NOW(),
    DELETED         BOOL        DEFAULT FALSE
);
DROP TABLE IF EXISTS CLUB_COMMUNITY.USER_CLUB;
# 사용자-소모임 N:M 매핑 테이블
# 사용자가 가입한 소모임을 의미한다.
# 소모임이 삭제되도 정보는 유지된다.
CREATE TABLE CLUB_COMMUNITY.USER_CLUB(
    ID              BIGINT      NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    USER_ID         BIGINT      NOT NULL,
    CLUB_ID         BIGINT      NOT NULL,
    CREATED_AT      TIMESTAMP   DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP   DEFAULT NOW() ON UPDATE NOW(),
    DELETED         BOOL        DEFAULT FALSE,
    UNIQUE(USER_ID, CLUB_ID)
);
DROP TABLE IF EXISTS CLUB_COMMUNITY.BOARDS;
# 게시판 테이블
# 기본적으로 자유 게시판이 존재하고 소모임이 추가될 때 마다 그 소모임에 해당하는 게시판이 추가된다.
# CLUB_ID가 NULL 이면 모든 사용자가 열람 가능하다.
# 소모임이 추가될때 추가되고 삭제될 때 삭제된다.
CREATE TABLE CLUB_COMMUNITY.BOARDS(
    ID              BIGINT      NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    CLUB_ID         BIGINT      DEFAULT NULL,
    BOARD_NAME      VARCHAR(16) NOT NULL UNIQUE,
    CREATED_AT      TIMESTAMP   DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP   DEFAULT NOW() ON UPDATE NOW(),
    DELETED         BOOL        DEFAULT FALSE
);
INSERT INTO CLUB_COMMUNITY.BOARDS(BOARD_NAME) VALUES('자유 게시판');
DROP TABLE IF EXISTS CLUB_COMMUNITY.POSTS;
# 게시글 테이블 : 제목, 내용을 입력받는다.
# 게시판 ID, 작성자 ID, 댓글 수, 조회수를 유지한다.
# 조회수는 별도의 검사 없이 게시글을 열람할 때 마다 올라간다.
CREATE TABLE CLUB_COMMUNITY.POSTS(
    ID              BIGINT      NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    BOARD_ID        BIGINT      NOT NULL,
    TITLE           VARCHAR(100)NOT NULL,
    CONTENT         TEXT,
    WRITER_ID       BIGINT      NOT NULL,
    COMMENT_NUM     INT         DEFAULT 0,
    HIT             INT         DEFAULT 0,
    CREATED_AT      TIMESTAMP   DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP   DEFAULT NOW() ON UPDATE NOW(),
    DELETED         BOOL        DEFAULT FALSE
);
DROP TABLE IF EXISTS CLUB_COMMUNITY.COMMENTS;
# 댓글 테이블 : 내용을 입력받는다.
# 게시글 ID, 작성자 ID를 유지한다.
# 대댓글은 허용하지 않는다.
CREATE TABLE CLUB_COMMUNITY.COMMENTS(
    ID              BIGINT      NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    POST_ID         BIGINT      NOT NULL,
    CONTENT         TEXT        NOT NULL,
    WRITER_ID       BIGINT      NOT NULL,
    CREATED_AT      TIMESTAMP   DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP   DEFAULT NOW() ON UPDATE NOW(),
    DELETED         BOOL        DEFAULT FALSE
);